"""Add model_api_keys table

Revision ID: 0104b68ff3a5
Revises: 6b2112c87519
Create Date: 2025-08-19 11:07:23.608299

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0104b68ff3a5"
down_revision: Union[str, Sequence[str], None] = "6b2112c87519"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_api_keys",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("api_key", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_model_api_keys__user_id__users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_api_keys")),
    )
    op.create_index(op.f("ix_model_api_keys__user_id"), "model_api_keys", ["user_id"], unique=False)
    op.add_column(
        "rubrics", sa.Column("judge_model", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rubrics", "judge_model")
    op.drop_index(op.f("ix_model_api_keys__user_id"), table_name="model_api_keys")
    op.drop_table("model_api_keys")
    # ### end Alembic commands ###
