"""update rubric defn

Revision ID: 22c6507954e1
Revises: 6335bfb185cb
Create Date: 2026-01-15 11:41:11.729836

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22c6507954e1"
down_revision: Union[str, Sequence[str], None] = "6335bfb185cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rubrics",
        sa.Column("prompt_templates", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("rubrics", sa.Column("output_parsing_mode", sa.String(length=50), nullable=True))
    op.add_column("rubrics", sa.Column("response_xml_key", sa.String(length=50), nullable=True))

    # Dangerous!
    # NOTE(mengk): this is fine, these have been deprecated for months now
    op.drop_column("rubrics", "exclusion_rules")
    op.drop_column("rubrics", "inclusion_rules")
    op.drop_column("rubrics", "high_level_description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
