"""add data table id to charts

Revision ID: 272b2376885b
Revises: 3e944ba3908f
Create Date: 2026-01-29 13:20:53.927549

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "272b2376885b"
down_revision: Union[str, Sequence[str], None] = "3e944ba3908f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("charts", sa.Column("data_table_id", sa.String(length=36), nullable=True))
    op.create_index(op.f("ix_charts__data_table_id"), "charts", ["data_table_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_charts__data_table_id__data_tables"),
        "charts",
        "data_tables",
        ["data_table_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_charts__data_table_id__data_tables"), "charts", type_="foreignkey")
    op.drop_index(op.f("ix_charts__data_table_id"), table_name="charts")
    op.drop_column("charts", "data_table_id")
    # ### end Alembic commands ###
