"""add filters table

Revision ID: 2cbd1a8d1894
Revises: 1f06faa655c4
Create Date: 2025-11-22 12:45:35.402143

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2cbd1a8d1894"
down_revision: Union[str, Sequence[str], None] = "1f06faa655c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filters",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("filter_dict", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_filters__collection_id__collections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_filters__created_by__users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_filters")),
    )
    op.create_index(op.f("ix_filters__collection_id"), "filters", ["collection_id"], unique=False)
    op.create_index(op.f("ix_filters__created_by"), "filters", ["created_by"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_filters__created_by"), table_name="filters")
    op.drop_index(op.f("ix_filters__collection_id"), table_name="filters")
    op.drop_table("filters")
    # ### end Alembic commands ###
