"""add is_clone to collections

Revision ID: 5c581f3bd108
Revises: 10c961252f56
Create Date: 2026-01-26 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c581f3bd108"
down_revision: Union[str, Sequence[str], None] = "10c961252f56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("collections", sa.Column("is_clone", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collections", "is_clone")
    # ### end Alembic commands ###
