"""cascade delete tables from collection id fk

Revision ID: 6387f7a8677b
Revises: 32bc3e96d06f
Create Date: 2025-11-13 15:11:03.337931

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6387f7a8677b"
down_revision: Union[str, Sequence[str], None] = "32bc3e96d06f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_agent_runs__collection_id__collections"), "agent_runs", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_agent_runs__collection_id__collections"),
        "agent_runs",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_analytics_events__collection_id__collections"),
        "analytics_events",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_analytics_events__collection_id__collections"),
        "analytics_events",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("fk_charts__collection_id__collections"), "charts", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_charts__collection_id__collections"),
        "charts",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_judge_result_centroids__centroid_id__rubric_centroids"),
        "judge_result_centroids",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_judge_result_centroids__centroid_id__rubric_centroids"),
        "judge_result_centroids",
        "rubric_centroids",
        ["centroid_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_judge_results__rubric_id_rubric_version__rubrics"),
        "judge_results",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_judge_results__agent_run_id__agent_runs"), "judge_results", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_judge_results__rubric_id_rubric_version__rubrics"),
        "judge_results",
        "rubrics",
        ["rubric_id", "rubric_version"],
        ["id", "version"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_judge_results__agent_run_id__agent_runs"),
        "judge_results",
        "agent_runs",
        ["agent_run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_refinement_agent_sessions__rubric_id_rubric_version__rubrics"),
        "refinement_agent_sessions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_refinement_agent_sessions__rubric_id_rubric_version__rubrics"),
        "refinement_agent_sessions",
        "rubrics",
        ["rubric_id", "rubric_version"],
        ["id", "version"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_rubric_centroids__collection_id__collections"),
        "rubric_centroids",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_rubric_centroids__rubric_id_rubric_version__rubrics"),
        "rubric_centroids",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_rubric_centroids__rubric_id_rubric_version__rubrics"),
        "rubric_centroids",
        "rubrics",
        ["rubric_id", "rubric_version"],
        ["id", "version"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_rubric_centroids__collection_id__collections"),
        "rubric_centroids",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_rubrics__collection_id__collections"), "rubrics", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_rubrics__collection_id__collections"),
        "rubrics",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_search_clusters__collection_id__collections"),
        "search_clusters",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_search_clusters__collection_id__collections"),
        "search_clusters",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_search_queries__collection_id__collections"), "search_queries", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_search_queries__collection_id__collections"),
        "search_queries",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_search_result_clusters__cluster_id__search_clusters"),
        "search_result_clusters",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_search_result_clusters__search_result_id__search_results"),
        "search_result_clusters",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_search_result_clusters__search_result_id__search_results"),
        "search_result_clusters",
        "search_results",
        ["search_result_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_search_result_clusters__cluster_id__search_clusters"),
        "search_result_clusters",
        "search_clusters",
        ["cluster_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_search_results__collection_id__collections"), "search_results", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_search_results__collection_id__collections"),
        "search_results",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_telemetry_agent_run_status__collection_id__collections"),
        "telemetry_agent_run_status",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_telemetry_agent_run_status__collection_id__collections"),
        "telemetry_agent_run_status",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_telemetry_logs__collection_id__collections"), "telemetry_logs", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_telemetry_logs__collection_id__collections"),
        "telemetry_logs",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_transcript_embeddings__collection_id__collections"),
        "transcript_embeddings",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_transcript_embeddings__collection_id__collections"),
        "transcript_embeddings",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_transcript_groups__collection_id__collections"),
        "transcript_groups",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_transcript_groups__collection_id__collections"),
        "transcript_groups",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_transcripts__collection_id__collections"), "transcripts", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_transcripts__collection_id__collections"),
        "transcripts",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("fk_views__collection_id__collections"), "views", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_views__collection_id__collections"),
        "views",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_views__collection_id__collections"), "views", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_views__collection_id__collections"),
        "views",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_transcripts__collection_id__collections"), "transcripts", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_transcripts__collection_id__collections"),
        "transcripts",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_transcript_groups__collection_id__collections"),
        "transcript_groups",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_transcript_groups__collection_id__collections"),
        "transcript_groups",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_transcript_embeddings__collection_id__collections"),
        "transcript_embeddings",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_transcript_embeddings__collection_id__collections"),
        "transcript_embeddings",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_telemetry_logs__collection_id__collections"), "telemetry_logs", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_telemetry_logs__collection_id__collections"),
        "telemetry_logs",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_telemetry_agent_run_status__collection_id__collections"),
        "telemetry_agent_run_status",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_telemetry_agent_run_status__collection_id__collections"),
        "telemetry_agent_run_status",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_search_results__collection_id__collections"), "search_results", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_search_results__collection_id__collections"),
        "search_results",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_search_result_clusters__cluster_id__search_clusters"),
        "search_result_clusters",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_search_result_clusters__search_result_id__search_results"),
        "search_result_clusters",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_search_result_clusters__search_result_id__search_results"),
        "search_result_clusters",
        "search_results",
        ["search_result_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_search_result_clusters__cluster_id__search_clusters"),
        "search_result_clusters",
        "search_clusters",
        ["cluster_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_search_queries__collection_id__collections"), "search_queries", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_search_queries__collection_id__collections"),
        "search_queries",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_search_clusters__collection_id__collections"),
        "search_clusters",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_search_clusters__collection_id__collections"),
        "search_clusters",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_rubrics__collection_id__collections"), "rubrics", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_rubrics__collection_id__collections"),
        "rubrics",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_rubric_centroids__collection_id__collections"),
        "rubric_centroids",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_rubric_centroids__rubric_id_rubric_version__rubrics"),
        "rubric_centroids",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_rubric_centroids__rubric_id_rubric_version__rubrics"),
        "rubric_centroids",
        "rubrics",
        ["rubric_id", "rubric_version"],
        ["id", "version"],
    )
    op.create_foreign_key(
        op.f("fk_rubric_centroids__collection_id__collections"),
        "rubric_centroids",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_refinement_agent_sessions__rubric_id_rubric_version__rubrics"),
        "refinement_agent_sessions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_refinement_agent_sessions__rubric_id_rubric_version__rubrics"),
        "refinement_agent_sessions",
        "rubrics",
        ["rubric_id", "rubric_version"],
        ["id", "version"],
    )
    op.drop_constraint(
        op.f("fk_judge_results__agent_run_id__agent_runs"), "judge_results", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_judge_results__rubric_id_rubric_version__rubrics"),
        "judge_results",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_judge_results__agent_run_id__agent_runs"),
        "judge_results",
        "agent_runs",
        ["agent_run_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_judge_results__rubric_id_rubric_version__rubrics"),
        "judge_results",
        "rubrics",
        ["rubric_id", "rubric_version"],
        ["id", "version"],
    )
    op.drop_constraint(
        op.f("fk_judge_result_centroids__centroid_id__rubric_centroids"),
        "judge_result_centroids",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_judge_result_centroids__centroid_id__rubric_centroids"),
        "judge_result_centroids",
        "rubric_centroids",
        ["centroid_id"],
        ["id"],
    )
    op.drop_constraint(op.f("fk_charts__collection_id__collections"), "charts", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_charts__collection_id__collections"),
        "charts",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_analytics_events__collection_id__collections"),
        "analytics_events",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_analytics_events__collection_id__collections"),
        "analytics_events",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_agent_runs__collection_id__collections"), "agent_runs", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_agent_runs__collection_id__collections"),
        "agent_runs",
        "collections",
        ["collection_id"],
        ["id"],
    )
    # ### end Alembic commands ###
