"""data tables

Revision ID: 665580d96b03
Revises: 10c961252f56
Create Date: 2026-01-12 23:22:35.765070

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "665580d96b03"
down_revision: Union[str, Sequence[str], None] = "10c961252f56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_tables",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("dql", sa.Text(), nullable=False),
        sa.Column("state_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_data_tables__collection_id__collections"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_data_tables__created_by__users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_tables")),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_data_tables__collection_id"),
        "data_tables",
        ["collection_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_data_tables__created_by"),
        "data_tables",
        ["created_by"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "telemetry_lineage", "derived_key", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    op.alter_column(
        "telemetry_lineage", "source_id", existing_type=sa.VARCHAR(length=128), nullable=False
    )
    op.alter_column("telemetry_lineage", "source_idx", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "telemetry_lineage",
        "attributes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "telemetry_lineage",
        "attributes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column("telemetry_lineage", "source_idx", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "telemetry_lineage", "source_id", existing_type=sa.VARCHAR(length=128), nullable=True
    )
    op.alter_column(
        "telemetry_lineage", "derived_key", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    op.drop_index(op.f("ix_data_tables__created_by"), table_name="data_tables")
    op.drop_index(op.f("ix_data_tables__collection_id"), table_name="data_tables")
    op.drop_table("data_tables")
    # ### end Alembic commands ###
