"""add versions to telemetry status

Revision ID: 71903b9a8ff7
Revises: b19c321c8291
Create Date: 2025-09-05 01:04:56.916930

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71903b9a8ff7"
down_revision: Union[str, Sequence[str], None] = "b19c321c8291"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telemetry_agent_run_status",
        sa.Column("current_version", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "telemetry_agent_run_status",
        sa.Column("processed_version", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telemetry_agent_run_status", "processed_version")
    op.drop_column("telemetry_agent_run_status", "current_version")
    # ### end Alembic commands ###
