"""move refinement to a json dump

Revision ID: 975db2dd2fb3
Revises: 5c5e0f0e7d18
Create Date: 2025-08-22 15:40:15.227553

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "975db2dd2fb3"
down_revision: Union[str, Sequence[str], None] = "5c5e0f0e7d18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refinement_agent_sessions",
        sa.Column(
            "content",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    # Note(mengk): this is fine because nobody on prod has run refinement session before.
    op.drop_column("refinement_agent_sessions", "messages")
    op.drop_column("refinement_agent_sessions", "pending_rubric")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
