"""add org roles

Revision ID: 9a1c94e22cbb
Revises: 0a5c90ee3e39
Create Date: 2025-12-12 22:34:04.518262

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a1c94e22cbb"
down_revision: Union[str, Sequence[str], None] = "0a5c90ee3e39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_organizations",
        sa.Column(
            "role",
            sa.Text(),
            nullable=False,
            server_default=sa.text("'member'"),
        ),
    )
    op.create_index(
        op.f("ix_user_organizations__role"), "user_organizations", ["role"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_organizations__role"), table_name="user_organizations")
    op.drop_column("user_organizations", "role")
    # ### end Alembic commands ###
