"""annotations

Revision ID: 9b87d6874efc
Revises: c2ff614e2a8b
Create Date: 2025-12-03 14:24:46.805770

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b87d6874efc"
down_revision: Union[str, Sequence[str], None] = "c2ff614e2a8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annotations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_annotations__agent_run_id__agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_annotations__collection_id__collections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_annotations__user_id__users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_annotations")),
    )
    op.create_index(
        op.f("ix_annotations__agent_run_id"), "annotations", ["agent_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_annotations__collection_id"), "annotations", ["collection_id"], unique=False
    )
    op.create_index(op.f("ix_annotations__user_id"), "annotations", ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_annotations__user_id"), table_name="annotations")
    op.drop_index(op.f("ix_annotations__collection_id"), table_name="annotations")
    op.drop_index(op.f("ix_annotations__agent_run_id"), table_name="annotations")
    op.drop_table("annotations")
    # ### end Alembic commands ###
