"""add id and fingerprint to api keys

Revision ID: 9d7efd738657
Revises: fcaa104207b6
Create Date: 2025-09-09 15:31:40.785715

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d7efd738657"
down_revision: Union[str, Sequence[str], None] = "fcaa104207b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_keys", sa.Column("key_id", sa.String(length=32), nullable=True))
    op.add_column("api_keys", sa.Column("fingerprint", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_api_keys__fingerprint"), "api_keys", ["fingerprint"], unique=True)
    op.create_index(op.f("ix_api_keys__key_id"), "api_keys", ["key_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_keys__key_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys__fingerprint"), table_name="api_keys")
    op.drop_column("api_keys", "fingerprint")
    op.drop_column("api_keys", "key_id")
    # ### end Alembic commands ###
