"""telemetry agent run status

Revision ID: aa3711c0cf33
Revises: 894f553e5699
Create Date: 2025-08-27 23:30:26.990500

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa3711c0cf33"
down_revision: Union[str, Sequence[str], None] = "894f553e5699"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telemetry_agent_run_status",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_telemetry_agent_run_status__collection_id__collections"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telemetry_agent_run_status")),
        sa.UniqueConstraint("agent_run_id", name="uq_telemetry_agent_run_status_agent_run_id"),
    )
    op.create_index(
        op.f("ix_telemetry_agent_run_status__agent_run_id"),
        "telemetry_agent_run_status",
        ["agent_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_agent_run_status__collection_id"),
        "telemetry_agent_run_status",
        ["collection_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_telemetry_agent_run_status__collection_id"),
        table_name="telemetry_agent_run_status",
    )
    op.drop_index(
        op.f("ix_telemetry_agent_run_status__agent_run_id"), table_name="telemetry_agent_run_status"
    )
    op.drop_table("telemetry_agent_run_status")
    # ### end Alembic commands ###
