"""rm unused tables and rename chat session table

Revision ID: b19c321c8291
Revises: 43165c6783d2
Create Date: 2025-09-04 17:53:50.359879

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b19c321c8291"
down_revision: Union[str, Sequence[str], None] = "43165c6783d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Removing unused tables
    op.drop_index(op.f("ix_diff_instances__paired_diff_result_id"), table_name="diff_instances")
    op.drop_table("diff_instances")
    op.drop_index(op.f("ix_diff_results__agent_run_1_id"), table_name="diff_results")
    op.drop_index(op.f("ix_diff_results__agent_run_2_id"), table_name="diff_results")
    op.drop_index(op.f("ix_diff_results__diff_query_id"), table_name="diff_results")
    op.drop_table("diff_results")
    op.drop_index(
        op.f("ix_paired_search_instance__paired_search_result_id"),
        table_name="paired_search_instance",
    )
    op.drop_table("paired_search_instance")
    op.drop_index(
        op.f("ix_paired_search_result__agent_run_1_id"), table_name="paired_search_result"
    )
    op.drop_index(
        op.f("ix_paired_search_result__agent_run_2_id"), table_name="paired_search_result"
    )
    op.drop_index(
        op.f("ix_paired_search_result__paired_search_query_id"), table_name="paired_search_result"
    )
    op.drop_table("paired_search_result")
    op.drop_index(op.f("ix_paired_search_query__collection_id"), table_name="paired_search_query")
    op.drop_index(
        op.f("ix_paired_search_query__diff_claims_result_id"), table_name="paired_search_query"
    )
    op.drop_table("paired_search_query")
    op.drop_index(op.f("ix_diff_claims_results__diff_query_id"), table_name="diff_claims_results")
    op.drop_table("diff_claims_results")
    op.drop_index(op.f("ix_diff_queries__collection_id"), table_name="diff_queries")
    op.drop_table("diff_queries")

    # Renaming chat sessions indices because of conflict with conventions
    op.drop_index(op.f("ix_chat_sessions_judge_result_id"), table_name="chat_sessions")
    op.create_index(
        op.f("ix_chat_sessions__judge_result_id"),
        "chat_sessions",
        ["judge_result_id"],
        unique=False,
    )
    op.drop_column("chat_sessions", "agent_run_ids")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
