"""fix transcript_groups.name inconsistency

Revision ID: b955627d29a6
Revises: d787aca9feff
Create Date: 2025-08-15 15:59:11.180299

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b955627d29a6"
down_revision: Union[str, Sequence[str], None] = "d787aca9feff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("transcript_groups", "name", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("transcript_groups", "name", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
