"""add sysprompt fields to SQLARubric

Revision ID: c14dd8b8762d
Revises: 8fdac2a6b2ac
Create Date: 2025-10-09 11:05:55.787369

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c14dd8b8762d"
down_revision: Union[str, Sequence[str], None] = "8fdac2a6b2ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rubrics", sa.Column("system_prompt_template", sa.Text(), nullable=True))
    op.add_column("rubrics", sa.Column("citation_instructions", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
