"""add transcript groups

Revision ID: d787aca9feff
Revises: fbae305069b5
Create Date: 2025-08-11 22:58:15.924325

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d787aca9feff"
down_revision: Union[str, Sequence[str], None] = "fbae305069b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transcript_groups",
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_transcript_group_id", sa.String(length=36), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_transcript_groups__collection_id__collections"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_transcript_group_id"],
            ["transcript_groups.id"],
            name=op.f("fk_transcript_groups__parent_transcript_group_id__transcript_groups"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_groups")),
    )
    op.create_index(
        op.f("ix_transcript_groups__collection_id"),
        "transcript_groups",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcript_groups__parent_transcript_group_id"),
        "transcript_groups",
        ["parent_transcript_group_id"],
        unique=False,
    )
    op.add_column(
        "transcripts", sa.Column("transcript_group_id", sa.String(length=36), nullable=True)
    )
    op.create_index(
        op.f("ix_transcripts__transcript_group_id"),
        "transcripts",
        ["transcript_group_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_transcripts__transcript_group_id__transcript_groups"),
        "transcripts",
        "transcript_groups",
        ["transcript_group_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_transcripts__transcript_group_id__transcript_groups"),
        "transcripts",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_transcripts__transcript_group_id"), table_name="transcripts")
    op.drop_column("transcripts", "transcript_group_id")
    op.drop_index(
        op.f("ix_transcript_groups__parent_transcript_group_id"), table_name="transcript_groups"
    )
    op.drop_index(op.f("ix_transcript_groups__collection_id"), table_name="transcript_groups")
    op.drop_table("transcript_groups")
    # ### end Alembic commands ###
