"""add created_at to agent runs

Revision ID: e4255c1640a7
Revises: 8077418780aa
Create Date: 2025-09-18 23:17:05.332338

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4255c1640a7"
down_revision: Union[str, Sequence[str], None] = "8077418780aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_runs", sa.Column("created_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_runs", "created_at")
    # ### end Alembic commands ###
