"""sync alembic

Revision ID: f78d9e891c5d
Revises: c14dd8b8762d
Create Date: 2025-10-09 11:40:03.403940

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f78d9e891c5d"
down_revision: Union[str, Sequence[str], None] = "c14dd8b8762d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_anthropic_compatible_backends_deleted_at"),
        table_name="anthropic_compatible_backends",
    )
    op.drop_index(
        op.f("ix_anthropic_compatible_backends_workspace_id"),
        table_name="anthropic_compatible_backends",
    )
    op.create_index(
        op.f("ix_anthropic_compatible_backends__deleted_at"),
        "anthropic_compatible_backends",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_anthropic_compatible_backends__workspace_id"),
        "anthropic_compatible_backends",
        ["workspace_id"],
        unique=False,
    )
    op.alter_column(
        "base_contexts",
        "tools",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_counterfactual_experiment_configs_anthropic_compatib_50b1"),
        table_name="counterfactual_experiment_configs",
    )
    op.create_index(
        op.f("ix_counterfactual_experiment_configs__anthropic_compatible_backend_id"),
        "counterfactual_experiment_configs",
        ["anthropic_compatible_backend_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_counterfactual_experiment_configs__deleted_at"),
        "counterfactual_experiment_configs",
        ["deleted_at"],
        unique=False,
    )
    op.drop_constraint(
        op.f("uq_counterfactual_experiment_results__experiment_config_id"),
        "counterfactual_experiment_results",
        type_="unique",
    )

    op.drop_index(
        op.f("ix_simple_rollout_config_anthropic_backends_backend_id"),
        table_name="simple_rollout_config_anthropic_backends",
    )
    op.drop_index(
        op.f("ix_simple_rollout_config_anthropic_backends_experiment__fff4"),
        table_name="simple_rollout_config_anthropic_backends",
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_config_backends_backend_id"),
        table_name="simple_rollout_experiment_config_backends",
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_config_backends_experiment_8f96"),
        table_name="simple_rollout_experiment_config_backends",
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_configs_base_context_id"),
        table_name="simple_rollout_experiment_configs",
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_configs_deleted_at"),
        table_name="simple_rollout_experiment_configs",
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_configs_judge_config_id"),
        table_name="simple_rollout_experiment_configs",
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_configs_workspace_id"),
        table_name="simple_rollout_experiment_configs",
    )
    op.create_index(
        op.f("ix_simple_rollout_experiment_configs__base_context_id"),
        "simple_rollout_experiment_configs",
        ["base_context_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simple_rollout_experiment_configs__deleted_at"),
        "simple_rollout_experiment_configs",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simple_rollout_experiment_configs__judge_config_id"),
        "simple_rollout_experiment_configs",
        ["judge_config_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simple_rollout_experiment_configs__workspace_id"),
        "simple_rollout_experiment_configs",
        ["workspace_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_results_collection_id"),
        table_name="simple_rollout_experiment_results",
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_results_experiment_config_id"),
        table_name="simple_rollout_experiment_results",
    )
    op.drop_constraint(
        op.f("uq_simple_rollout_experiment_results__experiment_config_id"),
        "simple_rollout_experiment_results",
        type_="unique",
    )
    op.create_index(
        op.f("ix_simple_rollout_experiment_results__collection_id"),
        "simple_rollout_experiment_results",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simple_rollout_experiment_results__experiment_config_id"),
        "simple_rollout_experiment_results",
        ["experiment_config_id"],
        unique=True,
    )
    op.drop_constraint(
        op.f("uq_tmp_investigator_authorized_users__user_id"),
        "tmp_investigator_authorized_users",
        type_="unique",
    )

    op.drop_index(op.f("idx_model_usage_byok_window"), table_name="model_usage")
    op.drop_index(
        op.f("idx_model_usage_free_window"),
        table_name="model_usage",
        postgresql_where="(api_key_id IS NULL)",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_tmp_investigator_authorized_users__user_id"),
        "tmp_investigator_authorized_users",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_results__experiment_config_id"),
        table_name="simple_rollout_experiment_results",
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_results__collection_id"),
        table_name="simple_rollout_experiment_results",
    )
    op.create_unique_constraint(
        op.f("uq_simple_rollout_experiment_results__experiment_config_id"),
        "simple_rollout_experiment_results",
        ["experiment_config_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_simple_rollout_experiment_results_experiment_config_id"),
        "simple_rollout_experiment_results",
        ["experiment_config_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simple_rollout_experiment_results_collection_id"),
        "simple_rollout_experiment_results",
        ["collection_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_configs__workspace_id"),
        table_name="simple_rollout_experiment_configs",
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_configs__judge_config_id"),
        table_name="simple_rollout_experiment_configs",
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_configs__deleted_at"),
        table_name="simple_rollout_experiment_configs",
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_configs__base_context_id"),
        table_name="simple_rollout_experiment_configs",
    )
    op.create_index(
        op.f("ix_simple_rollout_experiment_configs_workspace_id"),
        "simple_rollout_experiment_configs",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simple_rollout_experiment_configs_judge_config_id"),
        "simple_rollout_experiment_configs",
        ["judge_config_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simple_rollout_experiment_configs_deleted_at"),
        "simple_rollout_experiment_configs",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simple_rollout_experiment_configs_base_context_id"),
        "simple_rollout_experiment_configs",
        ["base_context_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simple_rollout_experiment_config_backends_experiment_8f96"),
        "simple_rollout_experiment_config_backends",
        ["experiment_config_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simple_rollout_experiment_config_backends_backend_id"),
        "simple_rollout_experiment_config_backends",
        ["backend_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simple_rollout_config_anthropic_backends_experiment__fff4"),
        "simple_rollout_config_anthropic_backends",
        ["experiment_config_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simple_rollout_config_anthropic_backends_backend_id"),
        "simple_rollout_config_anthropic_backends",
        ["backend_id"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("uq_counterfactual_experiment_results__experiment_config_id"),
        "counterfactual_experiment_results",
        ["experiment_config_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(
        op.f("ix_counterfactual_experiment_configs__deleted_at"),
        table_name="counterfactual_experiment_configs",
    )
    op.drop_index(
        op.f("ix_counterfactual_experiment_configs__anthropic_compatible_backend_id"),
        table_name="counterfactual_experiment_configs",
    )
    op.create_index(
        op.f("ix_counterfactual_experiment_configs_anthropic_compatib_50b1"),
        "counterfactual_experiment_configs",
        ["anthropic_compatible_backend_id"],
        unique=False,
    )
    op.alter_column(
        "base_contexts",
        "tools",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_anthropic_compatible_backends__workspace_id"),
        table_name="anthropic_compatible_backends",
    )
    op.drop_index(
        op.f("ix_anthropic_compatible_backends__deleted_at"),
        table_name="anthropic_compatible_backends",
    )
    op.create_index(
        op.f("ix_anthropic_compatible_backends_workspace_id"),
        "anthropic_compatible_backends",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_anthropic_compatible_backends_deleted_at"),
        "anthropic_compatible_backends",
        ["deleted_at"],
        unique=False,
    )

    op.create_index(
        op.f("idx_model_usage_free_window"),
        "model_usage",
        ["user_id", "bucket_start"],
        unique=False,
        postgresql_where="(api_key_id IS NULL)",
    )
    op.create_index(
        op.f("idx_model_usage_byok_window"),
        "model_usage",
        ["user_id", "api_key_id", "bucket_start"],
        unique=False,
    )
    # ### end Alembic commands ###
