"""add type and version to telemetry logs

Revision ID: fbae305069b5
Revises: 9d87e00ae5fd
Create Date: 2025-08-10 13:30:45.229172

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fbae305069b5"
down_revision: Union[str, Sequence[str], None] = "9d87e00ae5fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("telemetry_logs", sa.Column("type", sa.Text(), nullable=True))
    op.add_column("telemetry_logs", sa.Column("version", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telemetry_logs", "version")
    op.drop_column("telemetry_logs", "type")
    # ### end Alembic commands ###
