"""Make judge model required

Revision ID: fcaa104207b6
Revises: 77960404edb5
Create Date: 2025-09-08 14:28:45.908957

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fcaa104207b6"
down_revision: Union[str, Sequence[str], None] = "77960404edb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Update existing NULL judge_model values with a default model
    op.execute(
        """
        UPDATE rubrics
        SET judge_model = '{"provider": "openai", "model_name": "gpt-5", "reasoning_effort": "medium"}'
        WHERE judge_model IS NULL OR judge_model = 'null'::jsonb
    """
    )
    op.alter_column(
        "rubrics",
        "judge_model",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rubrics",
        "judge_model",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    # ### end Alembic commands ###
