from typing import Any, Literal, TypedDict, cast
from uuid import uuid4

import yaml
from pydantic import BaseModel, Field, SerializeAsAny, model_validator

from docent.data_models.metadata import BaseAgentRunMetadata
from docent.data_models.transcript import Transcript


class FilterableField(TypedDict):
    name: str
    type: Literal["str", "bool", "int", "float"]


class AgentRun(BaseModel):
    """Represents a complete run of an agent with transcripts and metadata.

    An AgentRun encapsulates the execution of an agent, storing all communication
    transcripts and associated metadata. It must contain at least one transcript.

    Attributes:
        id: Unique identifier for the agent run, auto-generated by default.
        name: Optional human-readable name for the agent run.
        description: Optional description of the agent run.
        transcripts: Dict mapping transcript IDs to Transcript objects.
        metadata: Additional structured metadata about the agent run.
    """

    id: str = Field(default_factory=lambda: str(uuid4()))
    name: str | None = None
    description: str | None = None

    transcripts: dict[str, Transcript]
    metadata: SerializeAsAny[BaseAgentRunMetadata]

    @model_validator(mode="after")
    def _validate_transcripts_not_empty(self):
        """Validates that the agent run contains at least one transcript.

        Raises:
            ValueError: If the transcripts list is empty.

        Returns:
            AgentRun: The validated AgentRun instance.
        """
        if len(self.transcripts) == 0:
            raise ValueError("AgentRun must have at least one transcript")
        return self

    @property
    def text(self) -> str:
        """Concatenates all transcript texts with double newlines as separators.

        Returns:
            str: A string representation of all transcripts.
        """

        transcripts_str = "\n\n".join(
            [
                f"<transcript {t_id}>\n{t.to_str()}\n</transcript {t_id}>"
                for t_id, t in self.transcripts.items()
            ]
        )

        # Gather metadata
        metadata_obj = self.metadata.model_dump(strip_internal_fields=True)
        if self.name is not None:
            metadata_obj["name"] = self.name
        if self.description is not None:
            metadata_obj["description"] = self.description

        yaml_width = float("inf")
        return (
            f"Here is a complete agent run for analysis purposes only:\n{transcripts_str}\n\n"
            f"Metadata about the complete agent run:\n<agent run metadata>\n{yaml.dump(metadata_obj, width=yaml_width)}\n</agent run metadata>"
        )

    def model_dump(self, *args: Any, **kwargs: Any) -> dict[str, Any]:
        """Extends the parent model_dump method to include the text property.

        Args:
            *args: Variable length argument list passed to parent method.
            **kwargs: Arbitrary keyword arguments passed to parent method.

        Returns:
            dict[str, Any]: Dictionary representation of the model including the text property.
        """
        return super().model_dump(*args, **kwargs) | {"text": self.text}

    def get_filterable_fields(self, max_depth: int = 1) -> list[FilterableField]:
        """Returns a list of all fields that can be used to filter the agent run,
        by recursively exploring the model_dump() for singleton types in dictionaries.

        Returns:
            list[FilterableField]: A list of filterable fields, where each field is a
                                   dictionary containing its 'name' (path) and 'type'.
        """

        result: list[FilterableField] = []

        def _explore_dict(d: dict[str, Any], prefix: str, depth: int):
            nonlocal result

            if depth > max_depth:
                return

            for k, v in d.items():
                if isinstance(v, (str, int, float, bool)):
                    result.append(
                        {
                            "name": f"{prefix}.{k}",
                            "type": cast(Literal["str", "bool", "int", "float"], type(v).__name__),
                        }
                    )
                elif isinstance(v, dict):
                    _explore_dict(cast(dict[str, Any], v), f"{prefix}.{k}", depth + 1)

        # Look at the agent run metadata
        _explore_dict(self.metadata.model_dump(strip_internal_fields=True), "metadata", 0)
        # Look at the transcript metadata
        # TODO(mengk): restore this later when we have the ability to integrate with SQL.
        # for t_id, t in self.transcripts.items():
        #     _explore_dict(
        #         t.metadata.model_dump(strip_internal_fields=True), f"transcript.{t_id}.metadata", 0
        #     )

        # Append the text field
        result.append({"name": "text", "type": "str"})

        return result
