import sys
from typing import Any
from uuid import uuid4

import yaml
from pydantic import BaseModel, Field, PrivateAttr, SerializeAsAny

from docent._llm_util.util import (
    get_token_count,
    group_messages_into_ranges,
    truncate_to_token_limit,
)
from docent.data_models.chat import AssistantMessage, ChatMessage, ContentReasoning
from docent.data_models.metadata import BaseMetadata

# Template for formatting individual transcript blocks
TRANSCRIPT_BLOCK_TEMPLATE = """
<{index_label} | role: {role}>
{content}
</{index_label}>
""".strip()

# Instructions for citing single transcript blocks
SINGLE_BLOCK_CITE_INSTRUCTION = "Each transcript block has a unique index; cite the relevant block index in brackets when relevant, like [B<idx>]. Use multiple tags to cite multiple blocks, like [B<idx1>][B<idx2>]. Use dashes to cite ranges, like [B<idx1>-B<idx2>], but cite ranges sparingly; do your best to be specific."

# Instructions for citing multiple transcript blocks
MULTI_BLOCK_CITE_INSTRUCTION = "Each transcript block has a unique index; cite the relevant block index in brackets when relevant, like [T<idx>B<idx>]. Use multiple tags to cite multiple blocks, like [T<idx1>B<idx1>][T<idx2>B<idx2>]. Use dashes to cite ranges, like [T<idx1>B<idx1>-T<idx2>B<idx2>], but cite ranges sparingly; do your best to be specific."


def format_chat_message(
    transcript_idx: int | None, block_idx: int | None, message: ChatMessage
) -> str:
    """Format a chat message with appropriate indexing and content presentation.

    Args:
        transcript_idx: Optional transcript index to include in the label.
        block_idx: Optional block index to include in the label.
        message: The chat message to format.

    Returns:
        str: Formatted chat message string with appropriate index labeling.
    """
    if transcript_idx is not None and block_idx is not None:
        index_label = f"T{transcript_idx}B{block_idx}"
    elif transcript_idx is not None:
        index_label = f"T{transcript_idx}"
    elif block_idx is not None:
        index_label = f"B{block_idx}"
    else:
        index_label = ""

    cur_content = ""

    # Add reasoning at beginning if applicable
    if isinstance(message, AssistantMessage) and message.content:
        for content in message.content:
            if isinstance(content, ContentReasoning):
                cur_content = f"<reasoning>\n{content.reasoning}\n</reasoning>\n"

    # Main content text
    cur_content += message.text

    # Update content in case there's a view
    if isinstance(message, AssistantMessage) and message.tool_calls:
        for tool_call in message.tool_calls:
            if tool_call.view:
                cur_content += f"\n<tool call>\n{tool_call.view.content}\n</tool call>"
            else:
                args = ", ".join([f"{k}={v}" for k, v in tool_call.arguments.items()])
                cur_content += f"\n<tool call>\n{tool_call.function}({args})\n</tool call>"

    return TRANSCRIPT_BLOCK_TEMPLATE.format(
        index_label=index_label, role=message.role, content=cur_content
    )


class Transcript(BaseModel):
    """Represents a transcript of messages in a conversation with an AI agent.

    A transcript contains a sequence of messages exchanged between different roles
    (system, user, assistant, tool) and provides methods to organize these messages
    into logical units of action.

    Attributes:
        id: Unique identifier for the transcript, auto-generated by default.
        name: Optional human-readable name for the transcript.
        description: Optional description of the transcript.
        messages: List of chat messages in the transcript.
        metadata: Additional structured metadata about the transcript.
    """

    id: str = Field(default_factory=lambda: str(uuid4()))
    name: str | None = None
    description: str | None = None

    messages: list[ChatMessage]
    metadata: SerializeAsAny[BaseMetadata] = Field(default_factory=BaseMetadata)

    _units_of_action: list[list[int]] | None = PrivateAttr(default=None)

    @property
    def units_of_action(self) -> list[list[int]]:
        """Get the units of action in the transcript.

        A unit of action represents a logical group of messages, such as a system message
        on its own or a user message followed by assistant responses and tool outputs.

        Returns:
            list[list[int]]: List of units of action, where each unit is a list of message indices.
        """
        if self._units_of_action is None:
            self._units_of_action = self._compute_units_of_action()
        return self._units_of_action

    def __init__(self, *args: Any, **kwargs: Any):
        super().__init__(*args, **kwargs)
        self._units_of_action = self._compute_units_of_action()

    def _compute_units_of_action(self) -> list[list[int]]:
        """Compute the units of action in the transcript.

        A unit of action is defined as:
        - A system prompt by itself
        - A group consisting of a user message, assistant response, and any associated tool outputs

        Returns:
            list[list[int]]: A list of units of action, where each unit is a list of message indices.
        """
        if not self.messages:
            return []

        units: list[list[int]] = []
        current_unit: list[int] = []

        def _start_new_unit():
            nonlocal current_unit
            if current_unit:
                units.append(current_unit.copy())
            current_unit = []

        for i, message in enumerate(self.messages):
            role = message.role
            prev_message = self.messages[i - 1] if i > 0 else None

            # System messages are their own unit
            if role == "system":
                assert not current_unit, "System message should be the first message"
                units.append([i])

            # User message always starts a new unit UNLESS the previous message was a user message
            elif role == "user":
                if current_unit and prev_message and prev_message.role != "user":
                    _start_new_unit()
                current_unit.append(i)

            # Start a new unit if the previous message was not a user or assistant message
            elif role == "assistant":
                if (
                    current_unit
                    and prev_message
                    and prev_message.role != "user"
                    and prev_message.role != "assistant"
                ):
                    _start_new_unit()
                current_unit.append(i)

            # Tool messages are part of the current unit
            elif role == "tool":
                current_unit.append(i)

            else:
                raise ValueError(f"Unknown message role: {role}")

        # Add the last unit if it exists
        _start_new_unit()

        return units

    def get_first_block_in_action_unit(self, action_unit_idx: int) -> int | None:
        """Get the index of the first message in a given action unit.

        Args:
            action_unit_idx: The index of the action unit.

        Returns:
            int | None: The index of the first message in the action unit,
                        or None if the action unit doesn't exist.

        Raises:
            IndexError: If the action unit index is out of range.
        """
        if not self._units_of_action:
            self._units_of_action = self._compute_units_of_action()

        if 0 <= action_unit_idx < len(self._units_of_action):
            unit = self._units_of_action[action_unit_idx]
            return unit[0] if unit else None
        return None

    def get_action_unit_for_block(self, block_idx: int) -> int | None:
        """Find the action unit that contains the specified message block.

        Args:
            block_idx: The index of the message block to find.

        Returns:
            int | None: The index of the action unit containing the block,
                        or None if no action unit contains the block.
        """
        if not self._units_of_action:
            self._units_of_action = self._compute_units_of_action()

        for unit_idx, unit in enumerate(self._units_of_action):
            if block_idx in unit:
                return unit_idx
        return None

    def set_messages(self, messages: list[ChatMessage]):
        """Set the messages in the transcript and recompute units of action.

        Args:
            messages: The new list of chat messages to set.
        """
        self.messages = messages
        self._units_of_action = self._compute_units_of_action()

    def to_str(
        self,
        transcript_idx_label: int | None = None,
        highlight_action_unit: int | None = None,
        max_action_unit_idx: int | None = None,
    ) -> str:
        """Convert the transcript to a string representation.

        Creates a formatted string representation of the transcript, optionally
        highlighting a specific action unit and limiting the number of action units shown.

        Args:
            transcript_idx_label: Optional transcript index to include in block labels.
            highlight_action_unit: Optional index of an action unit to highlight.
            max_action_unit_idx: Optional maximum action unit index to include in the output.
                If provided, only the first `max_action_unit_idx + 1` action units will be included.

        Returns:
            str: Formatted string representation of the transcript.

        Raises:
            ValueError: If highlight_action_unit or max_action_unit_idx is invalid.
        """
        return self.to_str_with_token_limit(
            token_limit=sys.maxsize,
            transcript_idx_label=transcript_idx_label,
            highlight_action_unit=highlight_action_unit,
            max_action_unit_idx=max_action_unit_idx,
        )[0]

    def to_str_with_token_limit(
        self,
        token_limit: int,
        transcript_idx_label: int | None = None,
        highlight_action_unit: int | None = None,
        max_action_unit_idx: int | None = None,
    ) -> list[str]:
        """Represents the transcript as a list of strings, each of which is at most token_limit tokens
        under the GPT-4 tokenization scheme.

        We'll try to split up long transcripts along message boundaries and include metadata.
        For very long messages, we'll have to truncate them and remove metadata.

        Returns:
            list[str]: A list of strings, each of which is at most token_limit tokens
            under the GPT-4 tokenization scheme.
        """
        if highlight_action_unit is not None and not (
            0 <= highlight_action_unit < len(self._units_of_action or [])
        ):
            raise ValueError(f"Invalid action unit index: {highlight_action_unit}")
        if max_action_unit_idx is not None and max_action_unit_idx >= len(
            self._units_of_action or []
        ):
            raise ValueError(f"Invalid max action unit index: {max_action_unit_idx}")

        # Format blocks by units of action
        au_blocks: list[str] = []
        for unit_idx, unit in enumerate(self._units_of_action or []):
            if max_action_unit_idx is not None and unit_idx > max_action_unit_idx:
                break

            unit_blocks: list[str] = []
            for msg_idx in unit:
                unit_blocks.append(
                    format_chat_message(transcript_idx_label, msg_idx, self.messages[msg_idx])
                )

            unit_content = "\n".join(unit_blocks)

            # Add highlighting if requested
            if highlight_action_unit and unit_idx == highlight_action_unit:
                blocks_str_template = "<HIGHLIGHTED>\n{}\n</HIGHLIGHTED>"
            else:
                blocks_str_template = "{}"
            au_blocks.append(
                blocks_str_template.format(
                    f"<action unit {unit_idx}>\n{unit_content}\n</action unit {unit_idx}>"
                )
            )
        blocks_str = "\n".join(au_blocks)

        # Gather metadata
        metadata_obj = self.metadata.model_dump(strip_internal_fields=True)
        if self.name is not None:
            metadata_obj["name"] = self.name
        if self.description is not None:
            metadata_obj["description"] = self.description

        yaml_width = float("inf")
        block_str = f"<blocks>\n{blocks_str}\n</blocks>\n"
        metadata_str = f"<metadata>\n{yaml.dump(metadata_obj, width=yaml_width)}\n</metadata>"

        metadata_token_count = get_token_count(metadata_str)
        block_token_count = get_token_count(block_str)

        if metadata_token_count + block_token_count <= token_limit:
            return [f"{block_str}" f"{metadata_str}"]
        else:
            results: list[str] = []
            block_token_counts = [get_token_count(block) for block in au_blocks]
            ranges = group_messages_into_ranges(
                block_token_counts, metadata_token_count, token_limit
            )
            for msg_range in ranges:
                if msg_range.include_metadata:
                    results.append(
                        f"<blocks>\n{"\n".join(au_blocks[msg_range.start:msg_range.end])}\n</blocks>\n"
                        f"{metadata_str}"
                    )
                else:
                    assert (
                        msg_range.end == msg_range.start + 1
                    ), "Ranges without metadata should be a single message"
                    result = str(au_blocks[msg_range.start])
                    if msg_range.num_tokens > token_limit - 10:
                        result = truncate_to_token_limit(result, token_limit - 10)
                    results.append(f"<blocks>\n{result}\n</blocks>\n")

            return results
