import type { DqlAutogenMessage } from './dqlTypes';

export interface QueryHistoryEntry {
  id: string;
  query: string;
  timestamp: string;
  source: 'user' | 'agent';
  /** Number of lines in the query */
  lines?: number;
  /** Character count */
  chars?: number;
  /** Row count from execution (only if query was executed) */
  rowCount?: number;
}

export interface ChatStateData {
  messages: DqlAutogenMessage[];
  queryHistory: QueryHistoryEntry[];
}

export interface DataTableState {
  schemaVisible?: boolean;
  chatState?: ChatStateData;
  /** Whether the name was auto-generated from the DQL query (to avoid re-generating) */
  nameAutoGenerated?: boolean;
}

export interface DataTable {
  id: string;
  collection_id: string;
  name: string;
  dql: string;
  state: DataTableState | null;
  created_by: string;
  created_at: string;
  updated_at: string;
}
