from docent.judges import Rubric

RUBRIC_GUIDELINES = """
The following rules govern how you should write rubrics and their schemas:

<Rubric guidelines>
    A rubric must contain exactly these components:
    - One paragraph with an insightful high-level framing that makes the ensuing specification highly simple and parsimonious. Usually, this requires identifying the correct abstractions and decision principles.
    - A decision procedure, specified as a natural-language decision tree, that anyone can follow to determine whether a transcript contains instances of a behavior. The procedure must be specific, unambiguous, and consistent: multiple humans should be able to agree on the outcome.
    - An output schema, specified as JSON Schema, that describes the output of the decision procedure. The output schema should strive to capture additional, important dimensions of the rubric and decision procedure. If outputs are too simple, certain decisions get flattened into oversimplified judgments that lose critical information about the decision procedure.

    Guidelines for creating and revising rubrics:
    - It's extremely important that the decision procedure is concise, simple, and clear. Each natural language predicate or decision point is an opportunity for ambiguity.
    - Create new versions (including the initial) of rubrics using the set_rubric_and_schema tool.
    - The initial version of a rubric should be especially short and sweet. You should work with the user over the course of the conversation to specify additional complexity. If you start with a long rubric, the user will be too overwhelmed to provide useful feedback.
    - Unless otherwise stated, revisions to the rubric should be as minimal and targeted as possible. Do not make gratuitous changes to wording unless absolutely necessary. As you generate each line of the revision, consult the last version of the rubric and consider whether your planned change is strictly necessary; if not, rewrite it exactly as it was before.
    - Users are permitted to update rubrics; when this happens, you will receive a user message with the new content and version of the rubric. No action is required on your part other than acknowledging what the user did and continuing where you left off.
    - Always rewrite the rubric w.r.t. the latest version, whether generated by you or the user.
</Rubric guidelines>

<Formatting instructions>
    - Format your answers and rubrics in Markdown.
    - To create a new line, use two newlines (\\n\\n).
    - Unordered lists (-), ordered lists (1.), and code ticks (` or ```) are permitted. All other forms of markup including bold, italics, and headings are strictly forbidden.
    - You may nest lists, but make sure to use the correct indentation.
    - Do not put the output schema in the rubric text.
</Formatting instructions>

<Output schema guidelines>
    - The schema must follow the JSON Schema standard.
    - The schema must NOT use nested objects or arrays.
    - The schema must NOT use any custom string formats such as dates or addresses.
    - There is a custom optional key "citations" (bool type) which may be added to string properties. If the judge model outputs a citation at this field, it will be parsed for the user.
</Output schema guidelines>
""".strip()

SELECTION_TAG = "SELECTED"
SELECTION_PROMPT = f"""
<User-provided selection>
    Notice that the user has selected a piece of text in the <{SELECTION_TAG}>...</{SELECTION_TAG}> tag. You are only permitted to rewrite content within the selection. Do NOT change any other text when rewriting the rubric.
</User-provided selection>
""".strip()

REWRITE_PROMPT = """
You are engaging in a rubric refinement process, where a user comes in with a vague idea of a behavior they are looking for in a dataset of AI agent run transcripts. Your job is to help the user write out a concrete specification of what they are looking for.

Please rewrite the rubric according to these instructions:

<User-provided instructions>
{instructions}
</User-provided instructions>

Here is the current rubric and schema:

<rubric_text>
{rubric}
</rubric_text>
<rubric_output_schema>
{rubric_output_schema}
</rubric_output_schema>

{rubric_guidelines}

Return the rewritten rubric and/or schema using the following XML tags. You may omit a tag entirely if you do not wish to modify that component (e.g., if the user's instructions only pertain to the rubric text, you may omit <rubric_output_schema>).

<rubric>
[Rubric text in Markdown]
</rubric>
<rubric_output_schema>
[Output schema in JSONSchema]
</rubric_output_schema>
""".strip()


def materialize_rewrite_prompt(
    rubric: Rubric, instructions: str, selection_indices: tuple[int, int] | None = None
) -> str:
    rubric_text_formatted = rubric.rubric_text
    rubric_guidelines = RUBRIC_GUIDELINES

    if selection_indices is not None:
        start, end = selection_indices
        if start < 0 or end < 0:
            raise ValueError(f"Selection indices must be non-negative, got ({start}, {end})")
        if start > end:
            raise ValueError(f"Start index must be <= end index, got ({start}, {end})")
        if end > len(rubric_text_formatted):
            raise ValueError(
                f"End index {end} exceeds rubric text length {len(rubric_text_formatted)}"
            )
        rubric_text_formatted = (
            rubric_text_formatted[:start]
            + f"<{SELECTION_TAG}>"
            + rubric_text_formatted[start:end]
            + f"</{SELECTION_TAG}>"
            + rubric_text_formatted[end:]
        )

        rubric_guidelines += f"\n\n{SELECTION_PROMPT}"

    return REWRITE_PROMPT.format(
        rubric=rubric_text_formatted,
        rubric_output_schema=rubric.output_schema,
        instructions=instructions,
        rubric_guidelines=rubric_guidelines,
    )
