name: Bridgewater Deploy

on:
  push:
    branches: [bridgewater]
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      deployment_id: bwater
      github_environment: bridgewater
      deploy_frontend_vercel: true
      vercel_environment: production
    secrets: inherit
