name: Staging Deploy

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      deployment_id: staging
      github_environment: staging
      # We use staging to test both deployment pathways
      deploy_frontend_apprunner: true
      deploy_frontend_vercel: true
      vercel_environment: staging
    secrets: inherit
